version: 2
jobs:
  build:
    branches:
      only:
        - circleci
    docker:
      - image: circleci/node:11.10.1
    steps:
      - checkout
      - run: #install yarn
          name: install-yarn
          command: sudo apt install yarn
      - run: #get dependencies
          name: get-dependencies
          command: yarn
      - run: #run tests
          name: start-server
          command: ENV_SILENT=true node server.js & ENV_SILENT=true node ace test && ENV_SILENT=true killall node
