version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.10.1
    steps:
      - checkout
      - run: #install yarn
          name: install-yarn
          command: sudo apt install yarn
      - run: #get dependencies
          name: get-dependencies
          command: yarn
      - run: #start server
          name: start-server
          command: ENV_SILENT=true node server.js & ENV_SILENT=true node ace test && killall node
